<?php
/**
 * Created by PhpStorm.
 * User: Jefferson Miranda
 * Date: 27/02/2020
 * Time: 21:09
 */

namespace tests\config;


use importador\config\Conn;
use PHPUnit\Framework\TestCase;

class TestConexao extends TestCase
{
    private $conn;


    private function fetch() {
        return ["database()" => "teste"];
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->conn =  $this->getMockBuilder(Conn::class)
            ->setConstructorArgs([new \PDO('sqlite::memory:')])
            ->getMock();

        $this->conn
            ->method("query")
            ->with("SELECT database()")
            ->willReturn($this);
    }

    public function testNameDatabase()
    {

        $database = $this->conn->query("SELECT database()")
            ->fetch(\PDO::FETCH_ASSOC)["database()"];

        $this->assertEquals('teste', $database, 'NOME DA CONEXAO COM O BANCO DE DADOS');
    }

}